name: Auth

on:
  pull_request:
    paths:
      - "Sources/Auth/**"
      - "Tests/AuthTests/**"
      - ".github/workflows/auth.yml"
  push:
    branches:
      - main
    paths:
      - "Sources/Auth/**"
      - "Tests/AuthTests/**"
      - ".github/workflows/auth.yml"

concurrency:
  group: auth-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Auth
    strategy:
      fail-fast: false
      matrix:
        config:
          - debug
          - release
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
      - name: Run tests
        run: CONFIG="${{ matrix.config }}" make test-auth

  test-linux:
    name: Test Auth (Linux)
    strategy:
      fail-fast: false
      matrix:
        swift-version: ["5.9", "5.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-deptch: 0
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}
      - run: make dot-env
      - name: Run tests
        run: swift test --filter AuthTests.
