name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library-darwin:
    runs-on: macos-14
    name: Test Library (Darwin)
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app
      - uses: actions/cache@v3
        with:
          path: /tmp/derived-data
          key: derived-data-cache-
      - name: Run tests
        run: make test-library

  library-evolution:
    name: Library (evolution, Darwin)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app
      - name: Build for library evolution
        run: make build-for-library-evolution

  examples:
    runs-on: macos-14
    name: Build Examples
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app
      - name: Prepare Examples Project
        run: cp Examples/Examples/_Secrets.swift Examples/Examples/Secrets.swift
      - name: Build examples
        run: make build-examples
