name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library-darwin:
    runs-on: macos-14
    name: Test Library (Darwin)
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - uses: actions/cache@v3
        with:
          path: tmp/derived-data
          key: derived-data-cache-
      - name: Run tests
        run: make test-library

  library-evolution:
    name: Library (evolution, Darwin)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Build for library evolution
        run: make build-for-library-evolution

  library-linux:
    runs-on: ubuntu-latest
    name: Test Library (Linux)
    strategy:
      matrix:
        swift-version: ["5.9", "5.10"]
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "${{ matrix.swift-version }}"
      - uses: actions/checkout@v3
      - name: Run Tests
        run: swift test

  library-windows:
    runs-on: windows-latest
    name: Test Library (Windows)
    steps:
      # We use BCNY's repo since they have newer builds of Swift
      # which have fixed libcurl in Foundation.
      - uses: compnerd/gha-setup-swift@main
        with:
          release-tag-name: "20231203.0"
          github-repo: "thebrowsercompany/swift-build"
          release-asset-name: installer-amd64.exe
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Run Tests
        run: swift test

  examples:
    runs-on: macos-14
    name: Build Examples
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Prepare Examples Project
        run: cp Examples/Examples/_Secrets.swift Examples/Examples/Secrets.swift
      - name: Build examples
        run: make build-examples
