name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library-swift-latest:
    name: Library
    runs-on: macos-14
    strategy:
      matrix:
        config:
          - debug
          - release
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
      - name: Build ${{ matrix.config }}
        run: make CONFIG=${{ matrix.config }} build-all-platforms
      - name: Run ${{ matrix.config }} tests
        run: make CONFIG=${{ matrix.config }} test-library

  # library-evolution:
  #   name: Library (evolution)
  #   runs-on: macos-14
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Select Xcode 15.4
  #       run: sudo xcode-select -s /Applications/Xcode_15.4.app
  #     - name: Build for library evolution
  #       run: make build-for-library-evolution

  library-compatibility:
    name: Library (Swift 5.9)
    runs-on: macos-14
    strategy:
      matrix:
        config:
          - debug
          - release
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Build ${{ matrix.config }}
        run: swift build -c ${{ matrix.config }}

  library-linux:
    name: Library (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-deptch: 0
      - uses: swift-actions/setup-swift@v2
      - name: Run tests
        run: swift test --skip IntegrationTests.

  examples:
    name: Examples
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
      - name: Build examples
        run: make build-examples