name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library:
    runs-on: macos-13
    name: Test Library
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
      - name: Run tests
        run: make test-library
