name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library:
    runs-on: macos-13
    name: Test Library
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.0.1
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
      - name: Run tests
        run: make test-library

  examples:
    runs-on: macos-13
    name: Build Examples
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.0.1
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
      - name: Build examples
        run: make build-examples

  check-breaking-changes:
    runs-on: macos-13
    name: Check for Breaking API Changes
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.0.1
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
      - run: |
          BASELINE_TREEISH=${{ github.base_ref }} \
            BASELINE_REPO_URL=${{ github.server_url }}/${{ github.repository }} \
            ./scripts/check-for-breaking-api-changes.sh
        
