name: Realtime

on:
  pull_request:
    paths:
      - "Sources/Realtime/**"
      - "Tests/RealtimeTests/**"
      - ".github/workflows/realtime.yml"
  push:
    branches:
      - main
    paths:
      - "Sources/Realtime/**"
      - "Tests/RealtimeTests/**"
      - ".github/workflows/realtime.yml"

concurrency:
  group: realtime-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Realtime
    strategy:
      fail-fast: false
      matrix:
        config:
          - debug
          - release
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.app
      - name: Run tests
        run: CONFIG="${{ matrix.config }}" make test-realtime
  test-linux:
    name: Test Realtime (Linux)
    strategy:
      fail-fast: false
      matrix:
        swift-version: ["5.9", "5.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-deptch: 0
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}
      - run: make dot-env
      - name: Run tests
        run: swift test --filter RealtimeTests.